#!/bin/bash
set -a
if [[ -f .env ]]; then
  # shellcheck disable=SC1091
  source .env
fi
set +a

export PYATTACKFORGE_LIVE="${PYATTACKFORGE_LIVE:-0}"
export ATTACKFORGE_VERIFY_SSL="${ATTACKFORGE_VERIFY_SSL:-1}"
export PYATTACKFORGE_RUN_USER_MUTATION_TESTS="${PYATTACKFORGE_RUN_USER_MUTATION_TESTS:-0}"
export PYATTACKFORGE_BELONGS_TO_LIBRARY="${PYATTACKFORGE_BELONGS_TO_LIBRARY:-Main Vulnerabilities}"
export PYATTACKFORGE_CLEANUP="${PYATTACKFORGE_CLEANUP:-1}"
